name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WinNetworkProcessMonitor
        path: |
          /home/runner/work/WinNetworkProcessMonitor/WinNetworkProcessMonitor/WinNetworkProcessMonitor/bin/Debug/net6.0/win-x64/publish/WinNetworkProcessMonitor.exe
          /home/runner/work/WinNetworkProcessMonitor/WinNetworkProcessMonitor/WinNetworkProcessMonitor/bin/Debug/net6.0/win-x64/iprules.txt
          /home/runner/work/WinNetworkProcessMonitor/WinNetworkProcessMonitor/WinNetworkProcessMonitor/bin/Debug/net6.0/win-x64/install_service.bat
